# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Just Animate
email: christopher.j.wallis@gmail.com
description: > # 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://just-animate.github.io" # the base hostname & protocol for your site
twitter_username: notoriousb1t
github_username:  notoriousb1t

# Build settings
#markdown: redcarpet
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: true
    css: class