# Site settings
title: Just Animate - Robust JavaScript animation library
description: > # this means to ignore newlines until "baseurl:"
  Just animate is a JavaScript animation library that plugs nicely into WAAPI
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://just-animate.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

assets:
  sources:
    - _assets/img
    - _assets/js
    - _assets/scss
  cache: true
  cdn: https://josephrexme.github.io/

timezone: America/Chicago
incremental: true
